### ISSUE TITLE
Create your participant file

### ISSUE THREAD

**Issue by swinton** [githubteacher/intro-to-github-june-2017#1]
Hello workshop participants! 👋 :octocat:

Let's show off how the [GitHub Flow](https://guides.github.com/introduction/flow/) works by creating our own participant [Markdown](https://guides.github.com/features/mastering-markdown/) files (like [my participant file](https://github.com/githubteacher/intro-to-github-june-2017/tree/master/participants/swinton.md)) here in this repository.

Note that we're collaborating in a single shared repo, avoiding the added friction of the [Fork & Pull Request model](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). Because we're simulating an "inside-your-company" environment, we know there's a baseline of trust in the developers to whom we've granted access.

Not to worry, we're still going to take steps to protect the integrity & quality of our [`master`](https://github.com/githubteacher/intro-to-github-june-2017/tree/master) branch. In this case, we're using a combination of [protected branches](https://help.github.com/articles/about-protected-branches/), [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/), and [required reviews](https://help.github.com/articles/approving-a-pull-request-with-required-reviews/). This ensures that changes are introduced via pull requests, and are reviewed by one of your peers.

Go ahead and navigate to the [`participants`](https://github.com/githubteacher/intro-to-github-june-2017/tree/master/participants) directory in the repo, then click "Create new file":

![Create new file button](https://cloud.githubusercontent.com/assets/4215/26660774/21c9db58-4648-11e7-9718-fb33bc9e9f2b.png)

After choosing a filename (try using your GitHub username!) and adding some content, make sure to select the "Create a new branch for this commit and start a pull request." option:

![Create new branch & PR](https://cloud.githubusercontent.com/assets/4215/26660813/7b44927c-4648-11e7-9302-5e06c29dcdb8.png)

**Comment by joeldlawler** [comment]
Wait a minute!  GitHub Evangelist?  What kind of cult is this?

**Comment by githubteacher** [comment]
:tada: @joeldlawler is now a repository collaborator. :balloon:

**Comment by mickpletcher** [comment]
Test comment

**Comment by joeldlawler** [comment]
Another comment.

**Comment by hoffbaud** [comment]
Leaving a comment in the comment box.

**Comment by comsynth** [comment]
this is a comment.

**Comment by michaelshacklett** [comment]
Doug needs to sign in

**Comment by dleins** [comment]
Forgot to sign in!  Works well now.   :+1:

**Comment by githubteacher** [comment]
:tada: @mickpletcher, @hoffbaud, @comsynth, @michaelshacklett, and @dleins are now  repository collaborators. :balloon:

**Comment by githubteacher** [comment]
We all :shipit: our participant files :boom:

Closing this out.
